apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-test
spec:
  replicas: 1
  selector:
    app: facebook
  template:
    metadata:
      name: pod1
      labels:
        app: facebook
    spec:
      containers:
        - name: cont1
          image: himanshutak8/app:v1

