apiVersion: v1
kind: Pod
metadata:
  name: wpdb
  labels:
    app: mysql
    job: database
spec:
  containers:
    - name: dbcont
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          #value: redhat [in simple way we pass the value like this]
          valueFrom:
            secretKeyRef:
              name: dbsecret   #Name should be the name of secret(resource name)
              key: dbpass
        - name: MYSQL_USER
          value: himanshu
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: dbpass
        - name: MYSQL_DATABASE
          value: wpdb
